<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="a-PC" name="Login Test" tests="2" failures="1" timestamp="21 May 2016 11:44:43 GMT" time="118.593" errors="0">
  <testcase name="doLogin" time="29.224" classname="com.qtpselenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="doLogin" time="82.245" classname="com.qtpselenium.facebook.pom.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="failure message">
      <![CDATA[java.lang.AssertionError: failure message
	at org.junit.Assert.fail(Assert.java:88)
	at com.qtpselenium.facebook.pom.testcases.base.BaseTest.reportFailure(BaseTest.java:74)
	at com.qtpselenium.facebook.pom.testcases.LoginTest.doLogin(LoginTest.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Login Test -->
