<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="a-PC" name="com.qtpselenium.facebook.pom.testcases.LoginTest" tests="2" failures="1" timestamp="21 May 2016 11:44:43 GMT" time="118.564" errors="0">
  <testcase name="doLogin" time="83.480" classname="com.qtpselenium.facebook.pom.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="failure message">
      <![CDATA[java.lang.AssertionError: failure message
	at org.junit.Assert.fail(Assert.java:88)
	at com.qtpselenium.facebook.pom.testcases.base.BaseTest.reportFailure(BaseTest.java:74)
	at com.qtpselenium.facebook.pom.testcases.LoginTest.doLogin(LoginTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:393)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </failure>
  </testcase> <!-- doLogin -->
  <testcase name="doLogin" time="35.084" classname="com.qtpselenium.facebook.pom.testcases.LoginTest"/>
</testsuite> <!-- com.qtpselenium.facebook.pom.testcases.LoginTest -->
